cp ../../JavaMOPAgent.jar spark/core/JavaMOPAgent.jar
cp ../../JavaMOPAgent.jar manifoldcf/framework/core/JavaMOPAgent.jar
cp ../../JavaMOPAgent.jar tika/tika-core/JavaMOPAgent.jar
cp ../../JavaMOPAgent.jar openwebbeans-meecrowave/meecrowave-core/JavaMOPAgent.jar
cp ../../JavaMOPAgent.jar wicket/wicket-util/JavaMOPAgent.jar
cp ../../JavaMOPAgent.jar deltaspike/deltaspike/core/impl/JavaMOPAgent.jar
cp ../../JavaMOPAgent.jar activemq-artemis/artemis-commons/JavaMOPAgent.jar
cp ../../JavaMOPAgent.jar tomee/container/openejb-core/JavaMOPAgent.jar
cp ../../JavaMOPAgent.jar directory-server/kerberos-codec/JavaMOPAgent.jar 
