---
title: "JULIETBench"
author: "Rodrigo Bonifácio et al."
date: "1/26/2022"
output: 
  html_document:
    theme: cerulean
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd(".")
library(sqldf)
library(xtable)
```

## Load the datasets

```{r load-mop}
mop <- read.csv("../results/mop.csv", head=T, sep=",")

colnames(mop)
nrow(mop)

sqldf("select spec, method, count(*) from mop  group by spec, method")

head(mop$className)

cmMop <- sqldf("select className, method, count(*) from mop group by className, method")

cc <- read.csv("../results/cognicrypt.csv", head=T, sep=",")

nrow(cc)
colnames(cc)

sqldf("select spec, method, count(*) from cc group by spec, method")

cmCC <- sqldf("select className, method, count(*) from cc group by className, method")

cg <- read.csv("../results/cryptoguard.csv", head=T, sep=",")

nrow(cg)
colnames(cg)

sqldf("select IssueRuleNumber, Method, count(*) from cg group by IssueRuleNumber, Method")

cg$ClassName <- substr(cg$ClassName, sapply(gregexpr("\\.", cg$ClassName), tail, 1) + 1, nchar(cg$ClassName))

cmCG <- sqldf("select ClassName as className, method as method, count(*) from cg group by className, method")

clogger <- read.csv("../results/crylogger.csv", head=T, sep=",")

colnames(clogger)
nrow(clogger)

sqldf("select spec, method, count(*) from clogger  group by spec, method")

head(clogger$className)

cmCrylogger <- sqldf("select className, method, count(*) from clogger group by className, method")

``` 



### Generate the Complete Dataset

```{r merge-warnings}
warnings <- sqldf("select className, method, 'mop' as tool from cmMop") 

warnings <- rbind(warnings, sqldf("select className, method, 'cc' as tool from cmCC") )

warnings <- rbind(warnings, sqldf("select className, method, 'cg' as tool from cmCG") )

warnings <- rbind(warnings, sqldf("select className, method, 'crylogger' as tool from cmCrylogger") )

warnings["CWE"] <- substring(warnings$className, 1, 6)

sqldf("select * from warnings where CWE not like 'CWE%'")

warnings <- sqldf("select * from warnings where CWE like 'CWE%'")

sqldf("select tool, count(*) from warnings group by tool")

cwes <- read.csv("../../cwes.csv", head=T, sep=',') 

cwes <- sqldf("select c.CWE, c.Description, count(distinct w.className) as total 
               from warnings w, cwes c 
               where c.cwe = w.cwe  and w.method like '%bad%'
               group by c.cwe, c.description 
               order by total")

xtable(cwes)

barplot(cwes$total, names=cwes$CWE)

# sqldf("select count(distinct className) from warnings")
```

### Ground Truth

```{r tp}
gt <- sqldf("select distinct CWE, className, method from warnings where method like '%bad%'")
nrow(gt)
```

## Computing Precision and Recall for MOP


```{r mop}
mop_tp = sqldf("select * 
            from warnings w
            where tool = 'mop' 
              and (w.className, w.method) in (select className, method from gt)")

mop_fp = sqldf("select * 
            from warnings w
            where tool = 'mop' 
              and (w.className, w.method) not in (select className, method from gt)")


mop_fn = sqldf("select CWE, className, method 
            from gt 
            where (className, method) not in (select className, method from warnings where tool = 'mop')")

nrow(mop_tp)
nrow(mop_fp)
nrow(mop_fn)


precision_mop = nrow(mop_tp) / (nrow(mop_tp) + nrow(mop_fp))

recall_mop = nrow(mop_tp) / (nrow(mop_tp) + nrow(mop_fn))

fmeasure_mop = 2 * ((precision_mop * recall_mop) / (precision_mop + recall_mop))


precision_mop

recall_mop

fmeasure_mop

```


## Computing Precision and Recall for CC


```{r cc}
cc_tp = sqldf("select * 
            from warnings w
            where tool = 'cc' 
              and (w.className, w.method) in (select className, method from gt)")

cc_fp = sqldf("select * 
            from warnings w
            where tool = 'cc' 
              and (w.className, w.method) not in (select className, method from gt)")


cc_fn = sqldf("select CWE, className, method 
            from gt 
            where (className, method) not in (select className, method from warnings where tool = 'cc')")


nrow(cc_tp)
nrow(cc_fp)
nrow(cc_fn)

precision_cc = nrow(cc_tp) / (nrow(cc_tp) + nrow(cc_fp))

recall_cc = nrow(cc_tp) / (nrow(cc_tp) + nrow(cc_fn))

fmeasure_cc = 2 * ((precision_cc * recall_cc) / (precision_cc + recall_cc))


precision_cc

recall_cc

fmeasure_cc

```


## Computing Precision and Recall for CG


```{r cg}

sqldf("select count(*) 
            from warnings w
            where tool = 'cg'")

cg_tp = sqldf("select * 
            from warnings w
            where tool = 'cg' 
              and (w.className, w.method) in (select className, method from gt)")

cg_fp = sqldf("select * 
            from warnings w
            where tool = 'cg' 
              and (w.className, w.method) not in (select className, method from gt)")


cg_fn = sqldf("select CWE, className, method 
            from gt 
            where (className, method) not in (select className, method from warnings where tool = 'cg')")


nrow(cg_tp)
nrow(cg_fp)
nrow(cg_fn)

precision_cg = nrow(cg_tp) / (nrow(cg_tp) + nrow(cg_fp))

recall_cg = nrow(cg_tp) / (nrow(cg_tp) + nrow(cg_fn))

fmeasure_cg = 2 * ((precision_cg * recall_cg) / (precision_cg + recall_cg))


precision_cg

recall_cg

fmeasure_cg

```

## Computing Precision and Recall for CryLogger


```{r crylogger}
cl_tp = sqldf("select * 
            from warnings w
            where tool = 'crylogger' 
              and (w.className, w.method) in (select className, method from gt)")

cl_fp = sqldf("select * 
            from warnings w
            where tool = 'crylogger' 
              and (w.className, w.method) not in (select className, method from gt)")


cl_fn = sqldf("select CWE, className, method 
               from gt 
               where (className, method) not in (select className, method from warnings where tool = 'crylogger')")

nrow(cl_tp)
nrow(cl_fp)
nrow(cl_fn)


precision_crylogger = nrow(cl_tp) / (nrow(cl_tp) + nrow(cl_fp))

recall_crylogger = nrow(cl_tp) / (nrow(cl_tp) + nrow(cl_fn))

fmeasure_crylogger = 2 * ((precision_crylogger * recall_crylogger) / (precision_crylogger + recall_crylogger))

precision_crylogger

recall_crylogger

fmeasure_crylogger

```


## Accuracy Results for JulietBench

```{r table}

Tools = c("MOP", "CogniCrypt", "CryptoGuard", "CryLogger")
Precision = c(precision_mop, precision_cc, precision_cg, precision_crylogger)
Recall = c(recall_mop, recall_cc, recall_cg, recall_crylogger)
FMeasure = c(fmeasure_mop, fmeasure_cc, fmeasure_cg, fmeasure_crylogger)

analysis_ds = data.frame(Tools, Precision, Recall, FMeasure)

analysis_ds

```


```{r}
mop <- sqldf("select distinct cwe,  className, 'RVSec' as tool, 'TP' as warning from mop_tp")
mop <- rbind(mop, sqldf("select distinct cwe,  className, 'RVSec' as tool, 'FP' as warning from mop_fp"))
mop <- rbind(mop, sqldf("select distinct cwe,  className, 'RVSec' as tool, 'FN' as warning from mop_fn"))

cc <- sqldf("select distinct cwe,  className, 'CogniCrypt' as tool, 'TP' as warning from cc_tp")
cc <- rbind(cc, sqldf("select distinct cwe,  className, 'CogniCrypt' as tool, 'FP' as warning from cc_fp"))
cc <- rbind(cc, sqldf("select distinct cwe,  className, 'CogniCrypt' as tool, 'FN' as warning from cc_fn"))

cg <- sqldf("select distinct cwe,  className, 'CryptoGuard' as tool, 'TP' as warning from cg_tp")
cg <- rbind(cg, sqldf("select distinct cwe,  className, 'CryptoGuard' as tool, 'FP' as warning from cg_fp"))
cg <- rbind(cg, sqldf("select distinct cwe,  className, 'CryptoGuard' as tool, 'FN' as warning from cg_fn"))

cl <- sqldf("select distinct cwe,  className, 'CryLogger' as tool, 'TP' as warning from cl_tp")
cl <- rbind(cl, sqldf("select distinct cwe,  className, 'CryLogger' as tool, 'FP' as warning from cl_fp"))
cl <- rbind(cl, sqldf("select distinct cwe,  className, 'CryLogger' as tool, 'FN' as warning from cl_fn"))

ds <- rbind(mop, cc)
ds <- rbind(ds, cg)
ds <- rbind(ds, cl)

sqldf("select tool, warning, count(*) from ds group by tool, warning")

write.csv(ds, "../results/gt-cwes.csv",  row.names = FALSE)

```