---
title: "OWASPBench"
author: "Rodrigo Bonifácio et al."
date: "1/26/2022"
output: 
  html_document:
    theme: cerulean
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd(".")
library(sqldf)
```

## Loading the base datasets (including the ground truth for LOC)


```{r load-gt}
gt <- read.csv("../results/datasets/gt.csv", head=T, sep=",")

colnames(gt)
nrow(gt)

# prune the ground truth. we are only interested in 
# the categories crypto and hash. 

gt <- sqldf("select TestCase, Category, Vulnerability, CWE 
             from gt
             where category in ('crypto', 'hash')")

nrow(gt)

sqldf("select CWE, Category, count(*) from gt group by CWE, Vulnerability")


sqldf("select count(*) from gt where vulnerability = 'true'")


cloc <- read.csv("../results/owasp-loc.csv", head=T, sep=',')

cloc <- sqldf("select ClassName, Code from cloc where Language='Java'")

nrow(cloc)

sqldf("select sum(code) from cloc")

# filtering the files with vulnerability in our GT

sqldf("select count(distinct className), sum(code) from cloc 
        where className in (select TestCase from gt)")
```

## MOP Analysis

```{r load-mop}
mop <- read.csv("../results/datasets/mop.csv", head=T, sep=",")

colnames(mop)
nrow(mop)

# lets prune the mop dataset, since we are only interested in 
# the categories crypto and hash

mop <- sqldf("select spec, className, cwe, count(*) warnings 
              from mop 
              where spec in ('CipherSpec', 'MessageDigestSpec')
              group by spec, className, cwe")


tp = sqldf("select * 
            from mop m
            where m.className in (select TestCase from gt where vulnerability = 'true')")

fp = sqldf("select * 
            from mop m
            where m.className not in (select TestCase from gt where vulnerability = 'true')")

fn = sqldf("select TestCase 
            from gt 
            where vulnerability = 'true' and TestCase not in (select className from mop)")

nrow(tp)
nrow(fp)
nrow(fn)

precision_mop = nrow(tp) / (nrow(tp) + nrow(fp))

recall_mop = nrow(tp) / (nrow(tp) + nrow(fn))

fmeasure_mop = 2 * ((precision_mop * recall_mop) / (precision_mop + recall_mop))

```

## CC Analysis

```{r load-cc}
cc <- read.csv("../results/datasets/cognicrypt.csv", head=T, sep=",")

colnames(cc)
nrow(cc)

# lets prune the cc dataset, since we are only interested in 
# the categories crypto and hash

cc <- sqldf("select spec, className, cwe, count(*) warnings 
              from cc 
              where spec in ('CipherSpec', 'MessageDigestSpec')
              group by spec, className")

nrow(cc)

tp = sqldf("select * 
            from cc c
            where c.className in (select TestCase from gt where vulnerability = 'true')")

fp = sqldf("select * 
            from cc c
            where c.className not in (select TestCase from gt where vulnerability = 'true')")

fn = sqldf("select TestCase 
            from gt 
            where vulnerability = 'true' and TestCase not in (select className from cc)")

nrow(tp)
nrow(fp)
nrow(fn)

precision_cc = nrow(tp) / (nrow(tp) + nrow(fp))

recall_cc = nrow(tp) / (nrow(tp) + nrow(fn))

fmeasure_cc = 2 * ((precision_cc * recall_cc) / (precision_cc + recall_cc))

```

## CG Analysis

```{r load-cg}
cg <- read.csv("../results/datasets/cryptoguard.csv", head=T, sep=",")

colnames(cg)
nrow(cg)

# lets prune the cc dataset, since we are only interested in 
# the categories crypto (1) and hash (2) 
 
cg <- sqldf("select spec, className, cwe, count(*) warnings 
              from cg
              where spec in (1, 2)   
              group by spec, className, cwe")

nrow(cg)

tp = sqldf("select * 
            from cg c
            where c.className in (select TestCase from gt where vulnerability = 'true')")

fp = sqldf("select * 
            from cg c
            where c.className not in (select TestCase from gt where vulnerability = 'true')")

fn = sqldf("select TestCase 
            from gt 
            where vulnerability = 'true' and TestCase not in (select className from cg)")


nrow(tp)
nrow(fp)
nrow(fn)

precision_cg = nrow(tp) / (nrow(tp) + nrow(fp))

recall_cg = nrow(tp) / (nrow(tp) + nrow(fn))

fmeasure_cg = 2 * ((precision_cg * recall_cg) / (precision_cg + recall_cg))

```


## CryLogger Analysis

```{r load-crylogger}
crylogger <- read.csv("../results/datasets/crylogger.csv", head=T, sep=",")

colnames(crylogger)
nrow(crylogger)

# lets prune the crylogger dataset, since we are only interested in 
# the categories crypto and hash

crylogger <- sqldf("select distinct spec, className, method, message, cwe
                   from crylogger 
                   where Spec in ('rule_R01', 'rule_R02', 'rule_R03')")

tp = sqldf("select * 
            from crylogger c
            where c.className in (select TestCase from gt where vulnerability = 'true')")

fp = sqldf("select * 
            from crylogger c
            where c.className not in (select TestCase from gt where vulnerability = 'true')")

fn = sqldf("select TestCase 
            from gt 
            where vulnerability = 'true' and TestCase not in (select className from crylogger)")


nrow(tp)
nrow(fp)
nrow(fn)


precision_crylogger = nrow(tp) / (nrow(tp) + nrow(fp))

recall_crylogger = nrow(tp) / (nrow(tp) + nrow(fn))

fmeasure_crylogger = 2 * ((precision_crylogger * recall_crylogger) / (precision_crylogger + recall_crylogger))

```

## Accuracy Results for OWASPBench

```{r table}
Tools = c("MOP", "CogniCrypt", "CryptoGuard", "CryLogger")
Precision = c(precision_mop, precision_cc, precision_cg, precision_crylogger)
Recall = c(recall_mop, recall_cc, recall_cg, recall_crylogger)
FMeasure = c(fmeasure_mop, fmeasure_cc, fmeasure_cg, fmeasure_crylogger)

analysis_ds = data.frame(Tools, Precision, Recall, FMeasure)

analysis_ds

```



# CWE integration

```{r}
nrow(gt)
colnames(gt)
sqldf("select CWE, VULNERABILITY, count(*) 
       from gt
       group by CWE, VULNERABILITY")

nrow(mop)
colnames(mop)

sqldf("select distinct spec from mop")

tp = sqldf("select g.CWE as 'cwe', g.TestCase as 'ClassName', 'RVSec' as Tool, 'TP' as 'Warning' 
            from mop m, gt g
            where m.className = g.TestCase and 
                  g.vulnerability = 'true'")

fp = sqldf("select m.cwe as 'cwe', m.className as 'ClassName', 'RVSec' as Tool, 'FP' as 'Warning' 
            from mop m
            where m.className not in (select TestCase from gt where vulnerability = 'true')")

fn = sqldf("select g.CWE as 'cwe', g.TestCase as 'ClassName', 'RVSec' as Tool, 'FN' as 'Warning' 
            from gt g
            where vulnerability = 'true' and TestCase not in (select className from mop)")

ds <- rbind(tp, fp)
ds <- rbind(ds, fn)
## CogniCrypt 

tp = sqldf("select g.CWE as 'cwe', g.TestCase as 'ClassName', 'CogniCrypt' as Tool, 'TP' as 'Warning' 
            from cc c, gt g 
            where c.className = TestCase and 
                  vulnerability = 'true'")

fp = sqldf("select c.CWE as 'cwe', c.className as 'ClassName', 'CogniCrypt' as Tool, 'FP' as 'Warning' 
            from cc c
            where c.className not in (select TestCase from gt where vulnerability = 'true')")


fn = sqldf("select g.CWE as 'cwe', g.TestCase as 'ClassName', 'CogniCrypt' as Tool, 'FN' as 'Warning' 
            from gt g
            where vulnerability = 'true' and TestCase not in (select className from cc)")

ds <- rbind(ds, tp)
ds <- rbind(ds, fp)
ds <- rbind(ds, fn)

## CryptoGuard 

tp = sqldf("select g.CWE as 'cwe', g.TestCase as 'ClassName', 'CryptoGuard' as Tool, 'TP' as 'Warning' 
            from cg c, gt g
            where c.className = TestCase and 
                  vulnerability = 'true'")

fp = sqldf("select c.CWE as 'cwe', c.className as 'ClassName', 'CryptoGuard' as Tool, 'FP' as 'Warning' 
            from cg c
            where c.className not in (select TestCase from gt where vulnerability = 'true')")


fn = sqldf("select g.CWE as 'cwe', g.TestCase as 'ClassName', 'CryptoGuard' as Tool, 'FN' as 'Warning' 
            from gt g
            where vulnerability = 'true' and TestCase not in (select className from cg)")

ds <- rbind(ds, tp)
ds <- rbind(ds, fp)
ds <- rbind(ds, fn)

## CryLogger 

tp = sqldf("select g.CWE as 'cwe', g.TestCase as 'ClassName', 'CryLogger' as Tool, 'TP' as 'Warning' 
            from crylogger c, gt g
            where c.className = TestCase and 
                  vulnerability = 'true'")

fp = sqldf("select c.cwe as 'cwe', c.className as 'ClassName', 'CryLogger' as Tool, 'FP' as 'Warning' 
            from crylogger c
            where c.className not in (select TestCase from gt where vulnerability = 'true')")

fn = sqldf("select g.CWE as 'cwe', g.TestCase as 'ClassName', 'CryLogger' as Tool, 'FN' as 'Warning'
            from gt g
            where vulnerability = 'true' and TestCase not in (select className from crylogger)")


ds <- rbind(ds, tp)
ds <- rbind(ds, fp)
ds <- rbind(ds, fn)

sqldf("select tool, warning, count(*) from ds group by tool, warning")

write.csv(ds, "../results/datasets/gt-cwes.csv",  row.names = FALSE)

sqldf("select tool, cwe, warning, count(*) 
       from ds 
       group by tool, cwe, warning")

```