---
title: "SmallCryptoAPIBench"
author: "Rodrigo Bonifácio et al."
date: "1/26/2022"
output: 
  html_document:
    theme: cerulean
    highlight: kate
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd(".")
library(sqldf)
library(xtable)
```

## Load the datasets (including the ground truth for MASCBench)

```{r load}
bench02mop <- read.csv("../results/mop.csv", head=T, sep=",")
bench02cc  <- read.csv("../results/cognicrypt.csv", head=T, sep=",")
bench02cg <- read.csv("../results/cryptoguard.csv", head=T, sep=",")
bench02crylogger <- read.csv("../results/crylogger.csv", head=T, sep=",")

gt <- read.csv("../results/bench02-gt-converted.csv", head=T, sep=",")

gt <- na.omit(gt)

```


## Identifying the sets of TPs and TNs

```{r}
gt <- sqldf("select propertyShortName, class, method, vulnerability, cwe
            from gt")

nrow(gt)

tp <- sqldf("select distinct class, cwe from gt where vulnerability = 'TRUE'")
tn <- sqldf("select distinct class, cwe from gt where vulnerability = 'FALSE'")

sqldf("select count(distinct class) from tp")
sqldf("select count(distinct class) from tn")
```

## Computing Precision and Recall for MOP

```{r}
# compute true positive 
mop_tp <- sqldf("select count(distinct className) as tp
                 from bench02mop 
                 where className in (select class from tp)")

# compute false positive 
mop_fp <- sqldf("select count(distinct className) as fp
                 from bench02mop 
                 where className in (select class from tn)")



# compute false-negative  
mop_fn <- sqldf("select count(distinct class) as fn
                 from tp 
                 where class not in (select className from bench02mop)")

# MOP true positives
mop_tp

# MOP false positives
mop_fp

# MOP false negatives
mop_fn



precision_mop <- mop_tp$tp / (mop_tp$tp + mop_fp$fp)
precision_mop

recall_mop <- mop_tp$tp / (mop_tp$tp + mop_fn$fn)
recall_mop

fmeasure_mop = (2 * precision_mop * recall_mop) / (precision_mop + recall_mop)
fmeasure_mop
```


## Computing Precision and Recall for CC

```{r}
# compute true positive 
cc_tp <- sqldf("select count(distinct className) as tp
                from bench02cc
                where className in (select class from tp)")

# compute false positive 
cc_fp <- sqldf("select count(distinct className) as fp
                from bench02cc
                where className in (select class from tn)")

# compute false-negative  
cc_fn <- sqldf("select count(distinct class) as fn
                from tp 
                where class not in (select className from bench02cc)")


# CC true positives
cc_tp

# CC false positives
cc_fp

# CC false negatives
cc_fn

precision_cc <- cc_tp$tp / (cc_tp$tp + cc_fp$fp)
precision_cc

recall_cc <- cc_tp$tp / (cc_tp$tp + cc_fn$fn)
recall_cc

fmeasure_cc = (2 * precision_cc * recall_cc) / (precision_cc + recall_cc)
fmeasure_cc
```

## Computing Precision and Recall for CG

```{r}

gtcg <- read.csv("../results/bench02-gt-cg-converted.csv", head=T, sep=",")

gtcg <- na.omit(gtcg)

gtcg <- sqldf("select propertyShortName, class, method, vulnerability, cwe
            from gtcg")

nrow(gtcg)

tpcg <- gtcg[gtcg$vulnerability == "TRUE",]
tncg <- gtcg[gtcg$vulnerability == "FALSE",]

# compute true positive 
cg_tp <- sqldf("select count(distinct className) as tp
                from bench02cg
                where className in (select class from tpcg)")

# compute false positive 
cg_fp <- sqldf("select count(distinct className) as fp
                from bench02cg
                where className in (select class from tncg)")

# compute false-negative  
cg_fn <- sqldf("select count(distinct class) as fn
                from tpcg 
                where class not in (select className from bench02cg)")


# CG true positives
cg_tp

# CC false positives
cg_fp

# CC false negatives
cg_fn

precision_cg <- cg_tp$tp / (cg_tp$tp + cg_fp$fp)
precision_cg

recall_cg <- cg_tp$tp / (cg_tp$tp + cg_fn$fn)
recall_cg

fmeasure_cg = (2 * precision_cg * recall_cg) / (precision_cg + recall_cg)
fmeasure_cg
```


## Computing Precision and Recall for CryLogger

```{r}
# compute true positive 
crylogger_tp <- sqldf("select count(distinct className) as tp
                 from bench02crylogger 
                 where className in (select class from tp)")

# compute false positive 
crylogger_fp <- sqldf("select count(distinct className) as fp
                 from bench02crylogger 
                 where className in (select class from tn)")



# compute false-negative  
crylogger_fn <- sqldf("select count(distinct class) as fn
                 from tp 
                 where class not in (select className from bench02crylogger)")

# MOP true positives
crylogger_tp

# MOP false positives
crylogger_fp

# MOP false negatives
crylogger_fn



precision_crylogger <- crylogger_tp$tp / (crylogger_tp$tp + crylogger_fp$fp)
precision_crylogger

recall_crylogger <- crylogger_tp$tp / (crylogger_tp$tp + crylogger_fn$fn)
recall_crylogger

fmeasure_crylogger = (2 * precision_crylogger * recall_crylogger) / (precision_crylogger + recall_crylogger)
fmeasure_crylogger
```


## Accuracy Results for SmallCryptoAPIBench

```{r table}

Tools = c("MOP", "CogniCrypt", "CryptoGuard", "CryLogger")
Precision = c(precision_mop, precision_cc, precision_cg, precision_crylogger)
Recall = c(recall_mop, recall_cc, recall_cg, recall_crylogger)
FMeasure = c(fmeasure_mop, fmeasure_cc, fmeasure_cg, fmeasure_crylogger)

analysis_ds = data.frame(Tools, Precision, Recall, FMeasure)

analysis_ds

```


```{r}
sqldf("select distinct className as fp
                 from bench02crylogger 
                 where className in (select class from tn)")


sqldf("select distinct class as fn
                 from tp 
                 where class not in (select className from bench02crylogger)")

sqldf("select * 
                 from bench02mop 
                 where className in (select class from tn)")

sqldf("select *
                 from tp 
                 where class not in (select className from bench02mop)")

```


## CWEs assessment 

```{r}
mop_tp <- sqldf("select distinct m.cwe as 'cwe', m.className as 'className', 'RVSec' as 'tool', 'TP' as 'Warning'
                 from bench02mop m  
                 where className in (select class from tp)")

# compute false positive 
mop_fp <- sqldf("select distinct m.cwe as 'cwe', m.className as 'className', 'RVSec' as 'tool', 'FP' as 'Warning'
                 from bench02mop m
                 where className in (select class from tn)")



# compute false-negative  
mop_fn <- sqldf("select distinct t.cwe as 'cwe', t.class as 'className', 'RVSec' as 'tool', 'FN' as 'Warning'
                 from tp t
                 where class not in (select className from bench02mop)")

ds <- rbind(mop_tp, mop_fp)
ds <- rbind(ds, mop_fn)


cc_tp <- sqldf("select distinct c.cwe as 'cwe', c.className as 'className', 'CogniCrypt' as 'tool', 'TP' as 'Warning'
                from bench02cc c
                where className in (select class from tp)")

# compute false positive 
cc_fp <- sqldf("select distinct c.cwe as 'cwe', c.className as 'className', 'CogniCrypt' as 'tool', 'FP' as 'Warning'
                from bench02cc c
                where className in (select class from tn)")

# compute false-negative  
cc_fn <- sqldf("select distinct t.cwe as 'cwe', t.class as 'className', 'CogniCrypt' as 'tool', 'FN' as 'Warning'
                from tp t
                where class not in (select className from bench02cc)")

ds <- rbind(ds, cc_tp)
ds <- rbind(ds, cc_fp)
ds <- rbind(ds, cc_fn)


# compute true positive 
cg_tp <- sqldf("select distinct c.cwe as 'cwe', c.className as 'className', 'CryptoGuard' as 'tool', 'TP' as 'Warning'
                from bench02cg c
                where className in (select class from tpcg)")

# compute false positive 
cg_fp <- sqldf("select  distinct c.cwe as 'cwe', c.className as 'className', 'CryptoGuard' as 'tool', 'FP' as 'Warning'
                from bench02cg c
                where className in (select class from tncg)")

# compute false-negative  
cg_fn <- sqldf("select  distinct t.cwe as 'cwe', t.class as 'className', 'CryptoGuard' as 'tool', 'FN' as 'Warning'
                from tpcg t
                where class not in (select className from bench02cg)")

ds <- rbind(ds, cg_tp)
ds <- rbind(ds, cg_fp)
ds <- rbind(ds, cg_fn)

crylogger_tp <- sqldf("select distinct c.cwe as 'cwe', c.className as 'className', 'CryLogger' as 'tool', 'TP' as 'Warning'
                 from bench02crylogger c
                 where className in (select class from tp)")

# compute false positive 
crylogger_fp <- sqldf("select distinct c.cwe as 'cwe', c.className as 'className', 'CryLogger' as 'tool', 'FP' as 'Warning'
                 from bench02crylogger c
                 where className in (select class from tn)")



# compute false-negative  
crylogger_fn <- sqldf("select distinct t.cwe as 'cwe', t.class as 'className', 'CryLogger' as 'tool', 'FN' as 'Warning'
                 from tp t
                 where class not in (select className from bench02crylogger)")

ds <- rbind(ds, crylogger_tp)
ds <- rbind(ds, crylogger_fp)
ds <- rbind(ds, crylogger_fn)

sqldf("select tool, warning, count(*) from ds group by tool, warning")

write.csv(ds, "../results/gt-cwes.csv",  row.names = FALSE)
```